[package]
name = "rust-ftp"
version = "0.1.0"
authors = ["xiaoboya <xiaoboya@troila.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
